name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    if: github.event_name == 'workflow_dispatch' && github.actor == 'sjunepark' && github.triggering_actor == 'sjunepark'
    uses: ./.github/workflows/validate.yml
    with:
      source_sha: ${{ github.sha }}

  standalone:
    if: github.event_name == 'workflow_dispatch' && github.actor == 'sjunepark' && github.triggering_actor == 'sjunepark'
    needs: validate
    uses: ./.github/workflows/standalone.yml
    with:
      source_sha: ${{ github.sha }}
      all_targets: true
